server.port=8082

spring.application.name=capiva-ai
spring.config.import=optional:configserver:http://localhost:8888

# Base de conhecimento interna
app.knowledge-base.path=classpath:knowledge/knowledge-base.txt